# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pedido',
            name='is_pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 2, 10, 52, 10, 244110)),
        ),
        migrations.AddField(
            model_name='pedido',
            name='is_pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(choices=[('D', 'Diario'), ('S', 'Semanal')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='comida',
            field=models.CharField(choices=[('L', 'Light'), ('R', 'Regular'), ('S', 'Saludable')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2016, 2, 2, 10, 52, 10, 243988)),
        ),
    ]
