# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0003_auto_20160204_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pedido',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 4, 22, 39, 26, 268990)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 4, 22, 39, 26, 266496)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2016, 2, 4, 22, 39, 26, 266377)),
        ),
    ]
