# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0004_auto_20160204_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 33, 40, 936907)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 33, 40, 934427)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 33, 40, 934312)),
        ),
    ]
