# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0005_auto_20160210_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 33, 55, 701824)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 33, 55, 697557)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 33, 55, 697445)),
        ),
    ]
