# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0015_auto_20160210_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_pedido',
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 18, 24, 55, 406184)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 18, 24, 55, 403672)),
        ),
    ]
