# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0033_auto_20160227_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'default_permissions': (), 'permissions': (('gestion_pedido', 'Gestion de Pedido'), ('consultar_pedido', 'Consulta de pedido'), ('modificar_pedido', 'Modificar pedido'), ('eliminar_pedido', 'Eliminar pedido'), ('crear_pedido', 'Crear pedido'), ('listar_pedido', 'Listar pedido'))},
        ),
    ]
