# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDelivery', '0002_auto_20160223_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={'default_permissions': (), 'permissions': (('gestion_zona', 'Gestion de zona'), ('consultar_zona', 'Consulta de zona'), ('modificar_zona', 'Modificar zona'), ('eliminar_zona', 'Eliminar zona'), ('crear_zona', 'Crear zona'), ('listar_zona', 'Listar zona'))},
        ),
    ]
