# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            options={
                'default_permissions': (),
                'permissions': (('gestion_rol', 'Gestion de Roles'), ('consulta_rol', 'Consultar Roles'), ('modificar_rol', 'Modificar Roles'), ('eliminar_rol', 'Eliminar Roles'), ('crear_rol', 'Crear Roles'), ('listar_rol', 'Listar Roles'), ('listar_permiso', 'Listar Permisos')),
            },
            bases=('auth.group',),
        ),
    ]
