# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPlatos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comida',
        ),
        migrations.DeleteModel(
            name='postre',
        ),
    ]
