# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionPlatos', '0006_auto_20160128_1457'),
        ('GestionClientes', '0003_auto_20160126_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.CharField(choices=[('LIGHT', 'Light'), ('REGULAR', 'Regular'), ('SALUDABLE', 'Saludable')], max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('costo', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(default=datetime.datetime.now)),
                ('costo_pedido', models.CharField(max_length=10)),
                ('factura', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='cod_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPedidos.pedido'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='postre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionPlatos.postre'),
        ),
    ]
