# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0004_cliente_direccion2'),
        ('GestionPedidos', '0002_auto_20160202_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=datetime.datetime(2016, 2, 4, 22, 31, 0, 589669))),
                ('cod_pedido', models.CharField(max_length=10)),
                ('cod_det_pedido', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 4, 22, 31, 0, 587265)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2016, 2, 4, 22, 31, 0, 587146)),
        ),
    ]
