# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0012_auto_20160210_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 57, 2, 407130)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='factura',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 57, 2, 404685)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 14, 57, 2, 404572)),
        ),
    ]
