# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0014_auto_20160210_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_pedido',
            old_name='cantidad',
            new_name='cantidad_comida',
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='cantidad_postre',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 18, 27, 47, 574768)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 18, 27, 47, 572240)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2016, 2, 10, 18, 27, 47, 572117)),
        ),
    ]
