# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0021_auto_20160211_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 21, 10, 48, 119429)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 21, 10, 48, 120418)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 21, 10, 48, 116911)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 21, 10, 48, 116797)),
        ),
    ]
