# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0025_pago_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_carga',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
