# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0026_auto_20160217_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
