# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0027_factura_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
