# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0030_detalle_pedido_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
