# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0031_pedido_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_pedido',
            options={'default_permissions': (), 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'default_permissions': (), 'permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'default_permissions': (), 'permissions': ()},
        ),
    ]
