# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0032_auto_20160222_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pedido',
            name='zona',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='zona',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
