# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPlatos', '0003_comida_postre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
