# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cod_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.cliente'),
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
