# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0003_auto_20160127_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cod_cliente',
        ),
        migrations.DeleteModel(
            name='pedido',
        ),
    ]
