# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruc_ci',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
