# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('telefono_2', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'default_permissions': (),
                'permissions': (('consulta_cliente', 'Consulta de Cliente'), ('modificar_cliente', 'Modificar Cliente'), ('eliminar_cliente', 'Eliminar Cliente'), ('crear_usuario', 'Crear Cliente'), ('listar_cliente', 'Listar Cliente')),
            },
        ),
    ]
