# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0003_auto_20160126_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
