# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0005_auto_20160225_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'default_permissions': (), 'permissions': (('gestion_cliente', 'Gestion de Cliente'), ('consulta_cliente', 'Consulta de Cliente'), ('modificar_cliente', 'Modificar Cliente'), ('eliminar_cliente', 'Eliminar Cliente'), ('crear_cliente', 'Crear Cliente'), ('listar_cliente', 'Listar Cliente'))},
        ),
    ]
