# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClientes', '0007_direccionesxcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='zona1',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='zona2',
        ),
    ]
